version: '2'
services:
    paisnaescola-app:
        image: paisnaescola
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://paisnaescola-mysql:3306/paisnaescola?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    paisnaescola-mysql:
        extends:
            file: mysql.yml
            service: paisnaescola-mysql
